module.exports = {
  PORT: 3001,
  SEARCH: 'search',
  HISTORY: 'History',
  CONNECTION: 'connection',
  CONNECTED: 'connected',
  DATABASE: 'nethub',
  USER: 'postgres',
  PASSWORD: 'password',
  QUERY: 'query',
  USERS: 'users',
  LANGUAGES: 'languages',
  MOVIES: 'Movies',
  MEDIA: 'media',
  MOVIE: 'movie',
  EPISODE: 'episode',
  SERIES: 'Series',
  RATING: 'Rating',
  REMAINING_EPISODES: 'Remaining Episodes',
  SUBTITLES: 'subtitles',
  NAME: 'Name',
  GENRE: 'Genre',
  DIRECTOR: 'Director',
  ACTOR: 'Actor',
  LANGUAGE: 'Language',
  INPUT: 'input',
  LOGIN: 'login'
}
