module.exports = {
  PORT: 3001,
  SEARCH: 'search',
  HISTORY: 'History',
  CONNECTION: 'connection',
  CONNECTED: 'connected',
  DATABASE: 'nethub',
  USER: 'postgres',
  PASSWORD: 'password',
  QUERY: 'query',
  MOVIES: 'Movies',
  SERIES: 'Series',
  NAME: 'Name',
  GENRE: 'Genre',
  DIRECTOR: 'Director',
  ACTOR: 'Actor',
  LANGUAGE: 'Language',
}
