module.exports = {
  PORT: 3001,
  SEARCH: 'search',
  HISTORY: 'History',
  CONNECTION: 'connection',
  CONNECTED: 'connected',
  DATABASE: 'nethub',
  USER: 'postgres',
  PASSWORD: 'password',
  QUERY: 'query',
  USERS: 'users',
  LANGUAGES: 'languages',
  MOVIES: 'Movies',
  MEDIA: 'media',
  MOVIE: 'movie',
  EPISODE: 'episode',
  SERIES: 'Series',
  RATING: 'Rating',
  REMAINING_EPISODES: 'Remaining Episodes',
  SUBTITLES: 'Subtitles',
  NAME: 'Name',
  GENRE: 'Genre',
  DIRECTOR: 'Director',
  ACTOR: 'Actor',
  LANGUAGE: 'Language',
  INPUT: 'input',
  LOGIN: 'login',
  UPDATE: 'update',
  SUBSCRIPTION: 'subscription',
  INSERT: 'insert',
  CHILDREN: 'children',
  MATURE_FILTER: 'mature filter',
  CONTENT_FILTER: 'content filter',
  METADATA: 'metadata',
  FILTERS: 'filters',
  SEASONS: 'seasons',
  ACTORS: 'actors',
  EPISODES: 'episodes',
  DIRECTORS: 'directors',
  GENRES: 'genres',
}
